# https://docs.travis-ci.com/user/languages/dart

language: dart

dart:
- stable
- dev

dart_task:
- test: --platform firefox
- dartanalyzer: --fatal-warnings lib/stagexl.dart

matrix:
  include:
    - dart: stable
    - dart_task:
        test: --platform dartium
        install_dartium: true
