name: stagexl
version: 1.4.6
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.11.0 <3.0.0'

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  byte_array: ^0.1.0
  tuple: ^2.0.0
  xml: ^5.3.0

dev_dependencies:
  test: ^1.17.0
  pedantic: ^1.11.0
  build_test: ^2.1.0
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
