name: stagexl
version: 2.0.1
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org
repository: https://github.com/bp74/StageXL

environment:
  sdk: '>=2.14.0 <3.0.0'

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  byte_array: ^1.0.0-nullsafety.0
  xml: ^5.3.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: any
  test: any
